pycom/pymakr-atom

lib/pymakr-view.js
Add button for WiFi SSID to Pymakr Atom. Allows a user to query the device's WLAN access point SSID when first setting the device up. Useful when in a room of many people trying to determine their WiFi AP SSID.
=> Added WiFi SSID Check

README.md
The manual installation path is incorrect. There's a typo on the installation path.
=> Correct typo on path

lib/main/settings-wrapper.js
As per the title of this PR, this patch allows using local DNS names as address in project or global settings. This comes handy when mDNS is used to advertise the telnet service in uPy.
=>  Allowing using local DNS names as address in settings

.gitignore, scripts/electron-compatibility-script.sh
Added a shell script which pulls the latest versions of Atom and Pymakr and checks if Pymakr is using the same Electron version than Atom's.
=> Added compatibility checker script

CHANGELOG.md, package-lock.json, package.json
Fixed minimum Atom version required to run Pymakr.
It must be >= 1.41.0, and not 1.40.0.
Pymakr 1.5.5 has been released with this fix.
=> Minimum atom version

CHANGELOG.md, lib/main.js, package-lock.json, package.json
Now Pymakr telling the user if it’s necessary to restart atom. Sometimes that's necessary.
=> Post-install feedback

lib/connections/device.js, lib/helpers/commands.js, package-lock.json
Fixed a timeout error when restart device is triggered. The device itself is successfully restarted anyway, but with a little bit of delay followed by a timeout exception printed in the logs. Now it's a way quicker and with no errors.
=> fix: fixed restart timeout

lib/config.js, lib/connections/device.js, lib/pymakr.js, lib/views/action-view.js, lib/views/info-view.js, lib/views/overlay-view.js, lib/views/panel-view.js, lib/views/sidebar-view.js, lib/views/snippets-view.js, lib/views/terminal.js, lib/wrappers/api-wrapper.js, package-lock.json, package.json, styles/pymakr.less, styles/xterm.css
Fix for the Pymakr resizer. I've updated xterm from 2 to 4 so I could make use of Fit addon for xterm. This addon will ensure the terminal is always 100% height and width. Sometimes, depending on Pymakr panel height (terminal's parent), there might be a little space underneath the terminal because, in that case, there's no space available to put one more line. Now changing font size has an immediate effect, no needs to restart atom anymore. I also added a little badge on buttons' tooltips showing the correspondent shortcut for that command. 
Since now I could finally manage to update the xterm to >3, the warning security might be gone after merging this PR.
=> Pb 892 resizer fix

lib/config.js, lib/main.js, lib/pymakr.js, lib/views/info-view.html, lib/views/panel-view.js, styles/pymakr.less
Improved UX from 'resizer', giving a smoother experience while resizing Pymakr. The terminal now has an anchor on the bottom of the available space, which means the line correction will now occur on the previous lines and not on the last anymore.
=> Improved Resizer

styles/pymakr.less
The connection tabs are now scrollable. 
This PR also fixes the connection tab overflow:
=> Connection tabs scrollable

keymaps/pycom-sync.json, lib/pymakr.js, menus/pycom-sync.json
This PR contains the following fixes:
- Toggle Command (Option + Control + T) not working.
- Multiple instances of Atom not being able to find devices on Pymakr. 
- Open on start setting not working. With that option disabled, Pymakr was not opening on Atom initialization but was not able to find devices too.
=> Pb 893 toggle terminal fix

lib/pymakr.js
Fixed a bug where Pymakr couldn't find the board by its name, causing unexpected tabs operations (closing, opening, closing all, opening all, tabs sync).
=> Fix open PyJTAG bug

package.json
Recently, xterm.js has been updated and the new version (4.6.0) of it is breaking Pymakr. This PR contains an update in package.json that locks xterm.js to 4.4.0
=> Fixed xterm recent bug

lib/views/panel-view.html, lib/views/sidebar-view.html, lib/views/sidebar-view.js
This PR contains the fix for the invisible Pybytes label in Pybytes button and also the not found console.error related to chrome-tabs.css
=> Fixed invisible Pybytes label in Pybytes button

styles/tabs.less
Somehow the way Atom provides stylesheet variables has been changed, which was making the close icon invisible. This PR contains the fix for that.
=> Close Icon Fix

CHANGELOG.md, package-lock.json, package.json, styles/tabs.less
=> Release 2.1.5

.github/workflows/main.yml, CHANGELOG.md, lib/features/sync/sync.js, lib/wrappers/settings-wrapper.js, package-lock.json, package.json
=> Release v2.1.9

lib/main.js, package-lock.json, package.json
Newest version of serialport now includes prebuilt bindings and I've added `fixbind` as a fallback solution.
`fixbind` is the bindings fallback solution from pymakr-vscode abstracted into a generalized package.
Next step, but low priority, would be to clean up the old tightly coupled binding solution.
=> fix: bindings were broke

.github/workflows/publish.yml, package-lock.json, package.json
Added automatic deployments, with similar setup as we have for VSCode.
Semantic-release is currently set to dry run in debug mode to make sure everything works.
---
Before we merge this release, we need to ensure that we have a `PUBLISHER_TOKEN` here https://github.com/pycom/pymakr-atom/settings/secrets/actions
If we already have a token for Atom under a different name, I can update the PR to use the correct name.
=> chore: added semantic-release

.github/workflows/publish.yml
We need a separate token (GH_TOKEN) with elevated rights, to be able to update changelog and package.json
=> chore: prepare for admin hook

CHANGELOG.md, lib/config.js, lib/views/terminal.js, lib/wrappers/settings-wrapper.js, package-lock.json, package.json
The terminal is currently locked to max 5000 lines of history. This patch makes the max scrollback lines configurable.
=> Feat configurable max scrollback
