pycom/pymakr-atom

- README.md
Added a section to advise users with devices that are not appearing to connect within the Pymakr console.
> Updated README.md for devices that will not connect to Pymakr console

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Added PR and issue templates
- Added CONTRIBUTING.md
- Minor changes in README.md
> Added templates and contributing guidelines

- CHANGELOG.md
- package-lock.json
- package.json
Updated readme and automatically updated version to 1.5.0 in package.json
> Release 1.5.0

- lib/board/shell.js
- lib/connections/connection.js
- lib/features/run/runner.js
- lib/features/sync/sync-helper.js
- lib/features/sync/sync.js
- lib/helpers/commands.js
- lib/pymakr.js
- lib/views/action-view.js
- lib/views/panel-view.html
- lib/views/panel-view.js
- lib/wrappers/api-wrapper.js
Pymakr now keeps the previous selected folder for every device. So if we change the selected device and go back, the selected project (folder) will remain persistent. 
This PR also contains two bug fixes:  
- the first load state bug, which is when loading the workspace at the first time can cause inconsistency in the current available projects on Pymakr.
- Wrong decoding at downloading files from device
> Persistent project by device

- CHANGELOG.md
- lib/config.js
- lib/connections/auto-connect.js
- lib/pymakr.js
- lib/views/info-view.js
- lib/views/panel-view.js
- package-lock.json
- scripts/download-binaries.js
- scripts/mp-download-atom.ps1
Pymakr 2 pre release. 
Bug fixes and preparations for Pymakr 2 release.
> Pb 877 pymakr 2 pre release

- CHANGELOG.md
- package-lock.json
- package.json
> Prepare 2.0.1

- lib/views/terminal.js
The default font size is 14, but not the minimum. This PR changes de minimum font size to 10.
> feat: updated minimum font size

- lib/board/authorize.js
- lib/connections/telnet/util-telnet.js
Fix for uncaught exception when connecting to device via Telnet.
> fix: fixed telnet connection uncaught exception

- lib/views/terminal.js
- styles/pymakr.less
> fix: removed terminal padding, fixing the terminal selection alignment

- lib/views/panel-view.js
Now the consistency between the connection state and the buttons/indicators is fixed.
> fix: fixed connection state inconsistency

- lib/connections/device.js
- lib/main.js
- lib/pymakr.js
- lib/views/action-view.js
- lib/views/info-view.js
- lib/views/sidebar-view.html
- lib/views/sidebar-view.js
- styles/assets/pycom-icon.svg
- styles/pymakr.less
- styles/tabs.less
- Fixed weird buggy artifact behind the terminal (light theme mode).
- Improved Pymakr colors to better match with atom's colors.
- Updated Pycom logo: now it's a SVG icon which uses the current Atom's text foreground color.
- Fixed connection tab hover color. 
- Improved spacing between right sidebar's items.
- Current active connection tab is now draggable.
- Placeholder background color now matches the terminal color.
> Minor layout fixes

- package-lock.json
- package.json
Merge the apm publish changes (version in package.json) into master
> Release 2.1.3

- CHANGELOG.md
- package.json
> Prepare release 2.1.4

- lib/features/sync/sync.js
> fix: throw-error method

- CHANGELOG.md
- package-lock.json
- package.json
> Release 2.1.5

- lib/features/sync/sync.js
- lib/wrappers/settings-wrapper.js
fix: atom confirm dialog
the dialog is not responding when passing an object with functions
should take a look later to update that
> fix: atom confirm dialog

- CHANGELOG.md
- package-lock.json
- package.json
> apm publish

- CHANGELOG.md
- package-lock.json
- package.json
> Release v2.1.8

- .github/workflows/main.yml
- CHANGELOG.md
- lib/features/sync/sync.js
- lib/wrappers/settings-wrapper.js
- package-lock.json
- package.json
> Release v2.1.9

- .gitignore
- lib/pymakr.js
- lib/views/panel-view.js
Before 
After
Also cleaned up convoluted code.
> Project improvements

- .github/workflows/publish.yml
(Hi! 👋 Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)
*(If it’s long, please paste to https://gist.github.com and insert the link here)*
**Operating system:**
**Atom version:**
**Pymakr version:**
> chore: removed dry version

- .github/workflows/publish.yml
(Hi! 👋 Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)
*(If it’s long, please paste to https://gist.github.com and insert the link here)*
**Operating system:**
**Atom version:**
**Pymakr version:**
> chore: no env secrets without env 🤦‍♂️

- .github/workflows/publish.yml
(Hi! 👋 Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)
*(If it’s long, please paste to https://gist.github.com and insert the link here)*
**Operating system:**
**Atom version:**
**Pymakr version:**
> missing env

- package-lock.json
- package.json
This branch is mainly for testing the serialport v10 beta.
1. `git clone --branch serialport-10-beta https://github.com/pycom/pymakr-atom.git`
2. `apm install`
3. `apm link`
serialport v10 produces an error in the developer tools, but still works.
The error:
```
Uncaught (in promise) Error: Cannot find module '@serialport/bindings'
Require stack:
- C:\Users\jakob\github\pymakr-atom\lib\main.js
- C:\Users\jakob\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html
at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
at Function.get_Module._resolveFilename (C:\Users\jakob\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:157920)
at Function.require.resolve …
```
> Serialport-10-beta
